[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
escrow = "5YuYrfNC8emUaLBbHcu7AvyxNRgbvp9B5TaDehFz9g9K"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
